export const myTableTemp = {
    tableAlias:'myTable',
    tableColumn:[
        {
            itemCaption:'日期',
            itemAlias:'date',
            fixed:'left',
            cStyle:{
                width:'150'
            }
        },
        {
            itemCaption:'姓名',
            itemAlias:'name',
            cStyle:{
                width:'150'
            }
        },{
            itemCaption:'省份',
            itemAlias:'province',
            cStyle:{
                width:'150'
            }
        },{
            itemCaption:'地址',
            itemAlias:'address',
            cStyle:{
                width:'150'
            }
        },{
            itemCaption:'城市',
            itemAlias:'city',
            cStyle:{
                width:'150'
            }
        },{
            itemCaption:'邮编',
            itemAlias:'zip',
            cStyle:{
                width:'150'
            }
        }
    ],
    toolbar:[
        {
            action:"check",
            buttonName:'查看',
            visible:true,
            type:'',
            disabled:true,
        },
        {
            action:"edit",
            buttonName:'编辑',
            visible:true,
            type:'',
            disabled:true,
        }
    ],
    listApi:'',
}